<?php

/**
 * @file
 * Tutorial module code.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function tutorial_field_widget_single_element_form_alter(&$element, FormStateInterface $form_state, $context) {
  $field_defininition = $context['items']
    ->getFieldDefinition();

  $field_name = method_exists($field_defininition, 'id') ? $field_defininition->id() : NULL;
  if ($field_name == 'node.tutorial.field_tut_body_image') {
    $element['#attached']['library'][] = 'tutorial/tutorial';
  }
}
